FROM node:10.5.0-alpine as node

WORKDIR /app

COPY . .

RUN npm i && npm audit fix 

#RUN npm rebuild node-sass
RUN npm run build --prod


FROM nginx:alpine
COPY --from=node /app/dist/dantakuti /usr/share/nginx/html